version: "3.8"

services:
  db:
    image: postgres:13.5
    container_name: tecsolfacil_db
    environment: 
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: tecsolfacil_dev
    ports:
      - 5432:5432
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - mynet

  tecsolfacil:
    stdin_open: true
    tty: true
    build:
      context: .
      target: build
    container_name: tecsolfacil
    command: iex -S mix phx.server
    restart: unless-stopped
    depends_on:
      - db
    ports: 
      - 4000:4000
    networks: 
      - mynet

networks:
  mynet:
    name: mynet

volumes:
  postgres_data: