name: GithubActions Pipeline CI

on: pull_request

jobs:
  checks:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        ports: ["5432:5432"]
        env:
          POSTGRES_PASSWORD: postgres
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@988e02bfe678367a02564f65ca2e37726dc0268f
        with:
          otp-version: "24.0"
          elixir-version: "1.13.0"
      - name: Restore dependencies cache
        uses: actions/cache@v2
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-
      - name: Get Deps
        run: mix deps.get
      - name: Check unused deps in lockfile
        run: mix deps.unlock --check-unused
      - name: Check compile warnings
        run: mix compile --warnings-as-errors
      - name: Check code formating
        run: mix format --check-formatted
      - name: Check code smells
        run: mix credo --strict
      - name: Check tests
        run: mix test --cover --warnings-as-errors --include integration
      - name: Check seeds consistency
        run: |
          mix ecto.create
          mix ecto.migrate
          mix run priv/repo/seeds.exs
